# Programming w/🐍 for Data Science 
<img src="https://github.com/habermanUIUC/CodeStories-lessons/blob/main/lessons/p4ds/ds/numpy1/html/section00.png?raw=True" align="left"/>

<a id="install"></a>
## Notebook Preparation for Lesson in 1•2•3 steps:
Each lesson will start with a similar template (given in the course schedule):  
1. **save** to your google drive (copy to drive)<br/><img src="https://github.com/habermanUIUC/CodeStories-lessons/blob/main/assets/images/colab/copy-to-drive.png?raw=True"/>
2. **update** the NET_ID to be your netID (no need to include @illinois.edu)
3. **run** the next cell to install the IDE. <img src="https://github.com/habermanUIUC/CodeStories-lessons/blob/main/assets/images/colab/play-button.png?raw=True"/>

In [83]:
LESSON_ID = 'p4ds:ds:numpy1'   # keep this as is
NET_ID    = 'jcarde28' # CHANGE_ME to your netID (keep the quotes)

def install_ide(net_id, lesson_id):
  import sys
  if 'codestories' not in sys.modules:
      print('installing modules')
      !pip install git+https://mehaberman@bitbucket.org/mehaberman/codestories.git --upgrade &> install.log
  
  from codestories.cs.CodeStories import CodeStory
  return CodeStory(net_id, lesson_id)

ide = install_ide(NET_ID, LESSON_ID)
print(ide.welcome())

Telling the story: Numerical Analysis with NumPy


# Lesson Numerical Analysis with NumPy
(hit ▶ to read the first part of the lesson️)

In [84]:
# run to read the next section
ide.reader.view_section(1)

# Python List vs Numpy Array

In [85]:
# run to read the next section
ide.reader.view_section(2)

In [86]:
import numpy as np

py_list = list(range(0,10))

# numpy's version of range
np_num  = np.arange(0,10)

print(type(np_num))
print(py_list)
print(np_num)

<class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


In [87]:
# run to read the next section
ide.reader.view_section(4)

# Array Creation

In [88]:
# run to read the next section
ide.reader.view_section(5)

In [89]:
# create an array from a Python list
data = np.array([1,2,3])
print(data)

[1 2 3]


In [90]:
# run to read the next section
ide.reader.view_section(7)

# Linspace (not a typo)

In [91]:
# run to read the next section
ide.reader.view_section(8)

In [92]:
# type&run the above example/exercise in this cell
x_axis = np.linspace(0,10,101)
x_axis

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

# Size and Shape

In [93]:
# run to read the next section
ide.reader.view_section(10)

In [94]:
# type&run the above example/exercise in this cell
np_num = np.arange(0,10)
print(np_num.size, np_num.shape)

10 (10,)


In [95]:
# run to read the next section
ide.reader.view_section(12)

# Operator Overload

In [96]:
# run to read the next section
ide.reader.view_section(13)

In [97]:
# type&run the above example/exercise in this cell

In [98]:
# run to read the next section
ide.reader.view_section(15)

In [99]:
# type&run the above example/exercise in this cell

In [100]:
# run to read the next section
ide.reader.view_section(17)

In [101]:
# type&run the above example/exercise in this cell

In [102]:
# run to read the next section
ide.reader.view_section(19)

In [103]:
miles = np.array([1,2,3])
kilometers = miles * 1.6
print(kilometers)

[1.6 3.2 4.8]


In [104]:
# run to read the next section
ide.reader.view_section(21)

In [105]:
data = np.array([1,2,3, np.nan])
print(data[3])
print(np.isnan(data[3]))

nan
True


# Simple Functions

In [106]:
# run to read the next section
ide.reader.view_section(23)

In [107]:
x = np.array([0,1,2,3,4,5,6])
print(np.sum(x))
print(x + 2*x)

21
[ 0  3  6  9 12 15 18]


In [108]:
# run to read the next section
ide.reader.view_section(25)

In [109]:
x = np.array([1,2,0,3,6,5,np.NaN,4])
print(np.nansum(x))
print(np.nanargmin(x))
print(np.nanargmax(x))

21.0
2
4


# 2D and beyond

In [110]:
# run to read the next section
ide.reader.view_section(27)

In [111]:
data = np.array([
  [1,  2, 3], 
  [4,  5, 6],  
  [7,  8, 9],  
  [10,11,12]]) 

print(data)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [112]:
# run to read the next section
ide.reader.view_section(29)

# Size, Dimension, Shape

In [113]:
# run to read the next section
ide.reader.view_section(30)

In [114]:
print(data.size, data.ndim)

12 2


In [115]:
# run to read the next section
ide.reader.view_section(32)

# Indexing

In [116]:
# run to read the next section
ide.reader.view_section(33)

In [117]:
one_d = np.array([1,2,3])
two_d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(one_d[1])
print(two_d[1])
print(two_d[1][1])

2
[4 5 6]
5


# Slicing And Dicing

In [118]:
# run to read the next section
ide.reader.view_section(35)

In [119]:
x = np.arange(100).reshape(20,5)
print("Rows 2,3,4 ", x[2:5])

# Advanced slicing
print("First 5 rows\n", x[:5])
print("Row 18 to the end\n", x[18:])
print("Last 5 rows\n", x[-5:])
print("Reverse the rows\n", x[::-1])

Rows 2,3,4  [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
First 5 rows
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Row 18 to the end
 [[90 91 92 93 94]
 [95 96 97 98 99]]
Last 5 rows
 [[75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
Reverse the rows
 [[95 96 97 98 99]
 [90 91 92 93 94]
 [85 86 87 88 89]
 [80 81 82 83 84]
 [75 76 77 78 79]
 [70 71 72 73 74]
 [65 66 67 68 69]
 [60 61 62 63 64]
 [55 56 57 58 59]
 [50 51 52 53 54]
 [45 46 47 48 49]
 [40 41 42 43 44]
 [35 36 37 38 39]
 [30 31 32 33 34]
 [25 26 27 28 29]
 [20 21 22 23 24]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


In [120]:
# run to read the next section
ide.reader.view_section(37)

In [121]:
data = np.arange(1,21).reshape(4,5)
print(data)
print(data[:2  , :3])     # two rows, three columns
print(data[:3:2, :4:2])   # ???

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[1 2 3]
 [6 7 8]]
[[ 1  3]
 [11 13]]


In [122]:
# run to read the next section
ide.reader.view_section(39)

# Operator Indirection and Masking

In [123]:
# run to read the next section
ide.reader.view_section(40)

In [124]:
np_num = np.arange(0,100,10) 
# [0,10,20,30,40,50,..,90]

np_idx = np.array([0,5,9])   
# want first sixth and last 

print(np_num[ np_idx ])      
# [0, 50, 90]

[ 0 50 90]


In [125]:
# run to read the next section
ide.reader.view_section(42)

In [126]:
np_num  = np.arange(0,10)
np_bool = np.array([True, False]*5)
np_wow  = np_num[np_bool]
print(np_wow)

[0 2 4 6 8]


In [127]:
# run to read the next section
ide.reader.view_section(44)

In [128]:
np_num  = np.arange(0,10)
np_bool = np_num < 5
print(np_num[np_bool])

[0 1 2 3 4]


In [129]:
# run to read the next section
ide.reader.view_section(46)

# Working with Strings

In [130]:
# run to read the next section
ide.reader.view_section(47)

In [131]:
fruit = np.array("apples,pears,bananas,oranges".split(','))
print(fruit)
lens = np.char.str_len(fruit)
print(lens)

['apples' 'pears' 'bananas' 'oranges']
[6 5 7 7]


In [132]:
# run to read the next section
ide.reader.view_section(49)

In [133]:
# type&run the above example/exercise in this cell
data = ['apple pear pizza',
        'apple lemon bagel milk lemon',
        'pizzza soda apple']
trips = np.array(data)

print(np.char.count(trips, 'apple'))

[1 1 1]


In [134]:
# run to read the next section
ide.reader.view_section(51)

# Lesson Assignment

In [135]:
# run to read the next section
ide.reader.view_section(52)

In [136]:
def display_data():
    import LessonUtil as Util
    p = Util.path_for_data('data.csv')
    with open(p, 'r') as fd:
       data = fd.read()
       print(data)

display_data()

Date;Merchant;Type;Price;Tax;Total
01/02/17;Bevande Café;Restaurant; 4.57 ; 0.41 ; 4.98
01/03/17;Papa Del's Pizza;Restaurant; 17.57 ; 1.58 ; 19.15
01/04/17;Radio Maria;Restaurant; 56.20 ; 5.06 ; 61.26
01/05/17;Bevande Café;Restaurant; 3.56 ; 0.32 ; 3.88
01/06/17;County Market;Grocery; 30.15 ; 2.71 ; 32.86
01/07/17;Papa Del's Pizza;Restaurant; 18.08 ; 1.63 ; 19.71
01/08/17;Bombay Indian Grill;Restaurant; 13.07 ; 1.18 ; 14.25
01/09/17;Lai Lai Wok;Restaurant; 20.67 ; 1.86 ; 22.53
01/10/17;Bevande Café;Restaurant; 1.99 ; 0.18 ; 2.17
01/11/17;Bombay Indian Grill;Restaurant; 20.07 ; 1.81 ; 21.88
01/12/17;Meijer;Grocery; 26.98 ; 2.43 ; 29.41
01/13/17;Bevande Café;Restaurant; 2.18 ; 0.20 ; 2.38
01/14/17;Café Kopi;Restaurant; 4.10 ; 0.37 ; 4.47
01/15/17;Bevande Café;Restaurant; 2.73 ; 0.25 ; 2.98
01/16/17;Bevande Café;Restaurant; 2.00 ; 0.18 ; 2.18
01/17/17;Radio Maria;Restaurant; 55.67 ; 5.01 ; 60.68
01/19/17;Bombay Indian Grill;Restaurant; 18.14 ; 1.63 ; 19.77
01/21/17;Apricot Lane;Apparel; 4

In [137]:
# run to read the next section
ide.reader.view_section(54)

In [138]:
import numpy as np
def q0(data):
  return np.sum(data['Total'])

def test_q0():
  import LessonUtil as Util
  data = Util.read_data()
  print(q0(data))

test_q0()

901.3900000000001


In [139]:
# run to read the next section
ide.reader.view_section(56)

In [140]:
def q1(data):                          
  return np.sum(data['Type'] == 'Restaurant')

def test_q1():
  import LessonUtil as Util
  data = Util.read_data()
  print(q1(data))

test_q1()

33


In [141]:
# run to read the next section
ide.reader.view_section(58)

In [142]:
# type&run the above example/exercise in this cell
def q2(data):                          
  return np.sum(data['Total'][data['Type'] == 'Restaurant'])

def test_q2():
  import LessonUtil as Util
  data = Util.read_data()
  print(q2(data))

test_q2()

407.98


In [143]:
# run to read the next section
ide.reader.view_section(60)

In [144]:
# type&run the above example/exercise in this cell
def q3(data):                          
  return np.sum(data['Tax'])

def test_q3():
  import LessonUtil as Util
  data = Util.read_data()
  print(q3(data))

test_q3()

74.42999999999999


In [145]:
# run to read the next section
ide.reader.view_section(62)

In [146]:
# type&run the above example/exercise in this cell
def q4(data):                          
  return np.sum(data['Tax'][data['Type'] == 'Grocery'])

def test_q4():
  import LessonUtil as Util
  data = Util.read_data()
  print(q4(data))

test_q4()

5.140000000000001


In [147]:
# run to read the next section
ide.reader.view_section(64)

In [148]:
# type&run the above example/exercise in this cell
def q5(data):                          
  return np.mean(data['Total'])

def test_q5():
  import LessonUtil as Util
  data = Util.read_data()
  print(q5(data))

test_q5()

21.985121951219515


In [149]:
# run to read the next section
ide.reader.view_section(66)

In [150]:
# type&run the above example/exercise in this cell
def q6(data):                          
  return np.mean(data['Total'][data['Total'] < 3])

def test_q6():
  import LessonUtil as Util
  data = Util.read_data()
  print(q6(data))

test_q6()

2.4019999999999997


In [151]:
# run to read the next section
ide.reader.view_section(68)

In [152]:
# type&run the above example/exercise in this cell
def q7(data):                          
  return np.sum(data['Total'][data['Total']%data['Total'] == 0])

def test_q7():
  import LessonUtil as Util
  data = Util.read_data()
  print(q7(data))

test_q7()

901.3900000000001


In [153]:
# run to read the next section
ide.reader.view_section(70)

In [157]:
# type&run the above example/exercise in this cell
def q8(data):                          
  merchants = data['Merchant'][np.char.str_len(data['Merchant']) < 7] # grab merchants with < 7 characters long

  total_sum = 0
  for merchant in merchants:
    total_sum += np.sum(data['Total'][data['Merchant'] == merchant])

  return total_sum

def test_q8():
  import LessonUtil as Util
  data = Util.read_data()
  print(q8(data))

test_q8()

35.12


In [159]:
# run to read the next section
ide.reader.view_section(72)

In [169]:
# type&run the above example/exercise in this cell
def q9(data):  
  mask = np.zeros(len(data['Merchant']))     

  total = 0               
  for i, merchant in enumerate(data['Merchant']):
    if 'Café' in merchant:
      mask[i] = 1
      total += 1

  mask = mask.astype(bool)

  return total

def test_q9():
  import LessonUtil as Util
  data = Util.read_data()
  print(q9(data))

test_q9()

10


In [160]:
# run to read the next section
ide.reader.view_section(74)

In [170]:
# type&run the above example/exercise in this cell
def q10(data):  
  mask = np.zeros(len(data['Merchant']))     

  total = 0               
  for i, merchant in enumerate(np.unique(data['Merchant'])):
    if 'Café' in merchant:
      mask[i] = 1
      total += 1

  mask = mask.astype(bool)

  return total

def test_q10():
  import LessonUtil as Util
  data = Util.read_data()
  print(q10(data))

test_q10()

4


# Test and Submit

In [ ]:
# run to read the next section
ide.reader.view_section(76)

In [172]:
# just pick one of these to use 
# print(ide.tester.test_notebook()) 
print(ide.tester.test_notebook(verbose=True)) 

# once you are ready -- run this 
ide.tester.download_solution()

Score 100/100

clean 10/10

numbers 10/10

top10 80.0/80
Questions Missed: {7}
numpy1.py contains valid python; it will be downloaded


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# Appendix: (but still very useful)

In [ ]:
# run to read the next section
ide.reader.view_section(78)

In [ ]:
# type&run the above example/exercise in this cell
np.random.seed(101)
values = np.random.randint(0,7,(10,))
print(values)

mask = values == 5
print(mask)

indices = np.where(mask)
print(len(indices), indices)

for idx in range(len(indices)):
  i = indices[idx]
  print(values[i])

In [ ]:
# run to read the next section
ide.reader.view_section(80)

In [ ]:
# type&run the above example/exercise in this cell

In [ ]:
# run to read the next section
ide.reader.view_section(82)