# Linear algebra with Numpy

Linear algebra in Python can be done with [Numpy](http://www.numpy.org/).


> NumPy is the fundamental package for scientific computing with Python. It contains among other things: [...]
 useful linear algebra, Fourier transform, and random number capabilities.

In this Colab you will:

- Manipulate matrices;
- Solve Matrix equations;
- Calculate Matrix inverse and determinants.

## Manipulating matrices

It is straightforward to create a Matrix using Numpy. Let us consider the following as a examples:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
B = \begin{pmatrix}
14 & -2 & 12\\
4 & 4 & 5\\
5 & 5 & 1
\end{pmatrix}
$$


First, similarly to Sympy, we need to import Numpy:

In [ ]:
import numpy as np





Now we can define $A$:

In [ ]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

In [ ]:
A

matrix([[ 5,  6,  2],
        [ 4,  7, 19],
        [ 0,  3, 12]])

Define $B$ with the values defined above and print result. 

In [ ]:
# Student Solution Here

We can do basic manipulations in straightforward manner.

Multiply the $A$ matrix by 5 using the '*' operator.

In [ ]:
# Student solution here


Determine $A$ cubed by using the '**' as the exponent operator: 


In [ ]:
#Student solution here

Add $A$ and $B$ with the standard '+' operator:

In [ ]:
# Student solution here

Subtract $A$ and $B$ with the standard '-' operator:

In [ ]:
# Student solution here

Multiply $A$ and $B$ together with the '*' operator:

In [ ]:
# Student solution here

---

**EXERCISE** Compute $A ^ 2 - 2 A + 3$ with:

$$A = 
\begin{pmatrix}
1 & -1\\
2 & 1
\end{pmatrix}
$$

---

In [ ]:
# Student solution here



## Solving Matrix equations

We can use Numpy to (efficiently) solve large systems of equations of the form:

$$Ax=b$$

Let us illustrate that with:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
b = \begin{pmatrix}
-1\\
2\\
1 
\end{pmatrix}
$$

In [ ]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
b = np.matrix([[-1], [2], [1]])

We use the `linalg.solve` command to solve for $x$.   The use of the commands is `np.linalg.solve(A matrix, b matrix)`.  Use this command with the $A$ and $b$ you just defined to solve for $x$. 

In [ ]:
# Student solution here

Verify your result by multiplying $A$ by the $x$ solution you just found.  The result should obviously be $b$. 

In [ ]:
# Student solution here

matrix([[-1.],
        [ 2.],
        [ 1.]])

---

**EXERCISE** Compute the solutions to the matrix equation $Bx=b$ (using the $B$ defined earlier and the $b$ you just defined).

---

In [ ]:
# Student solution here



## Matrix inversion and determinants

Computing the inverse of a matrix is straightforward:

In [ ]:
Ainv = np.linalg.inv(A)
Ainv

matrix([[-0.20930233,  0.51162791, -0.7751938 ],
        [ 0.37209302, -0.46511628,  0.6744186 ],
        [-0.09302326,  0.11627907, -0.08527132]])

We can verify that $A^{-1}A=\mathbb{1}$:

In [ ]:
A * Ainv

matrix([[  1.00000000e+00,   2.77555756e-17,   3.05311332e-16],
        [ -2.08166817e-16,   1.00000000e+00,  -2.08166817e-16],
        [  5.55111512e-17,  -5.55111512e-17,   1.00000000e+00]])

The above might not look like the identity matrix but if you look closer you see that the diagonals are all `1` and the off diagonals are a **very** small number (which from a computer's point of view is `0`).

To calculate the determinant:

In [ ]:
np.linalg.det(A)

-128.99999999999997



**EXERCISE** Compute the inverse and determinant of $B$ (defined previously).




In [ ]:
# Student solution here