# Linear algebra with Numpy

Linear algebra in Python can be done with [Numpy](http://www.numpy.org/).


> NumPy is the fundamental package for scientific computing with Python. It contains among other things: [...]
 useful linear algebra, Fourier transform, and random number capabilities.

In this Colab you will:

- Manipulate matrices;
- Solve Matrix equations;
- Calculate Matrix inverse and determinants.

## Manipulating matrices

It is straightforward to create a Matrix using Numpy. Let us consider the following as a examples:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
B = \begin{pmatrix}
14 & -2 & 12\\
4 & 4 & 5\\
5 & 5 & 1
\end{pmatrix}
$$


First, similarly to Sympy, we need to import Numpy:

In [1]:
import numpy as np





Now we can define $A$:

In [2]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

In [12]:
print(A)

[[ 5  6  2]
 [ 4  7 19]
 [ 0  3 12]]


Define $B$ with the values defined above and print result. 

In [13]:
B = A
print(B)

[[ 5  6  2]
 [ 4  7 19]
 [ 0  3 12]]


We can do basic manipulations in straightforward manner.

Multiply the $A$ matrix by 5 using the '*' operator.

In [16]:
A*5

matrix([[25, 30, 10],
        [20, 35, 95],
        [ 0, 15, 60]])


Determine $A$ cubed by using the '**' as the exponent operator: 


In [19]:
A**3

matrix([[ 557, 1284, 3356],
        [ 760, 2305, 6994],
        [ 288, 1074, 3519]])

Add $A$ and $B$ with the standard '+' operator:

In [20]:
A+B

matrix([[10, 12,  4],
        [ 8, 14, 38],
        [ 0,  6, 24]])

Subtract $A$ and $B$ with the standard '-' operator:

In [21]:
A-B

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

Multiply $A$ and $B$ together with the '*' operator:

In [22]:
A*B

matrix([[ 49,  78, 148],
        [ 48, 130, 369],
        [ 12,  57, 201]])

---

**EXERCISE** Compute $A ^ 2 - 2 A + 3$ with:

$$A = 
\begin{pmatrix}
1 & -1\\
2 & 1
\end{pmatrix}
$$

---

In [23]:
A**2 - 2*A + 3

matrix([[ 42,  69, 147],
        [ 43, 119, 334],
        [ 15,  54, 180]])



## Solving Matrix equations

We can use Numpy to (efficiently) solve large systems of equations of the form:

$$Ax=b$$

Let us illustrate that with:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
b = \begin{pmatrix}
-1\\
2\\
1 
\end{pmatrix}
$$

In [25]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
b = np.matrix([[-1], [2], [1]])

We use the `linalg.solve` command to solve for $x$.   The use of the commands is `np.linalg.solve(A matrix, b matrix)`.  Use this command with the $A$ and $b$ you just defined to solve for $x$. 

In [29]:
x = np.linalg.solve(A,b)
x

matrix([[ 0.45736434],
        [-0.62790698],
        [ 0.24031008]])

Verify your result by multiplying $A$ by the $x$ solution you just found.  The result should obviously be $b$. 

In [30]:
A*x

matrix([[-1.],
        [ 2.],
        [ 1.]])

---

**EXERCISE** Compute the solutions to the matrix equation $Bx=b$ (using the $B$ defined earlier and the $b$ you just defined).

---

In [31]:
np.linalg.solve(B,b)

matrix([[ 0.45736434],
        [-0.62790698],
        [ 0.24031008]])



## Matrix inversion and determinants

Computing the inverse of a matrix is straightforward:

In [32]:
Ainv = np.linalg.inv(A)
Ainv

matrix([[-0.20930233,  0.51162791, -0.7751938 ],
        [ 0.37209302, -0.46511628,  0.6744186 ],
        [-0.09302326,  0.11627907, -0.08527132]])

We can verify that $A^{-1}A=\mathbb{1}$:

In [33]:
A * Ainv

matrix([[ 1.00000000e+00,  4.99600361e-16, -2.77555756e-17],
        [ 1.38777878e-16,  1.00000000e+00,  1.80411242e-16],
        [ 1.11022302e-16,  1.11022302e-16,  1.00000000e+00]])

The above might not look like the identity matrix but if you look closer you see that the diagonals are all `1` and the off diagonals are a **very** small number (which from a computer's point of view is `0`).

To calculate the determinant:

In [34]:
np.linalg.det(A)

-129.00000000000009



**EXERCISE** Compute the inverse and determinant of $B$ (defined previously).




In [35]:
Binv = np.linalg.inv(B)
print(Binv)

det = np.linalg.det(B)
print(det)

[[-0.20930233  0.51162791 -0.7751938 ]
 [ 0.37209302 -0.46511628  0.6744186 ]
 [-0.09302326  0.11627907 -0.08527132]]
-129.00000000000009
